standard_robot_pp_ros2:
  ros__parameters:
    device_name: /dev/ttyACM0
    baud_rate: 115200
    flow_control: none
    parity: none
    stop_bits: "1"
    set_detector_color: false
    record_rosbag: true
    debug: false


robot_decision:
  ros__parameters:
    goal_points:  # 目标点坐标数组（对应代码中的rmul_goal_point）
    
    #BLUE
      x: [-0.8, 4.9, 5.0, 2.0, 6.0, 0.0]   # 必须包含至少4个坐标
      y: [-5.8, 1.9, -3.5, -3.5, 6.0, 0.0]  # 与x数组长度严格一致
      z: [0.0, 0.0, 0.0, 0.0, 0.4, 0.0]   # 默认平面运动场景
    #RED
      #x: [21.8, 9.5, 5.0, 2.0, 5.5, 0.0]   # 必须包含至少4个坐标
      #y: [6.0, 2.8, -3.5, -3.0, 6.1, 0.0]  # 与x数组长度严格一致
      #z: [0.0, 0.0, 0.0, 0.0, 0.4, 0.0]   # 默认平面运动场景
      
      #x: [21.8, 9.5, 5.0, 2.0, 5.5, 0.0]   # 必须包含至少4个坐标
      #y: [6.0, 2.8, -3.5, -3.0, 6.1, 0.0]  # 与x数组长度严格一致
      #z: [0.0, 0.0, 0.0, 0.0, 0.4, 0.0]   # 默认平面运动场景
      # - {x: 1.5, y: 0.0}   # 索引0：常规目标点
      # - {x: 2.0, y: 1.0}   # 索引1：随机目标点1
      # - {x: 2.0, y: -1.0}  # 索引2：随机目标点2
      # - {x: 0.5, y: 0.0}   # 索引3：回防点

    time_thresholds:  # 时间阶段阈值（单位：秒）
      abundant: 420    # 时间充足阈值
      normal: 320      # 时间正常阈值
      tense: 150        # 时间紧张阈值
      critical: 60     # 极度紧张阈值

    hp_thresholds:    # 血量判断阈值
      abundant:  # 时间充足阶段
        high: 400      # 高血量阈值
        medium: 250    # 中血量阈值
        low: 150        # 低血量阈值
      normal:    # 时间正常阶段
        high: 400      # 高血量阈值
        medium: 250     # 中血量阈值
        low: 150        # 低血量阈值
      tense:     # 时间紧张阶段
        high: 400
        medium: 250
        low: 150
      critical:  # 极度紧张阶段
        high: 400
        medium: 250
        low: 150

    decision_config:
      path_tolerance: 0.2  # 路径执行容差（米）
      nav2_action_server: "/navigate_to_pose"  # 导航动作服务名称

joint_state_publisher:
  ros__parameters:
    use_sim_time: false
    rate: 200
    source_list: ["serial/gimbal_joint_state"]
    offset_timestamp: 0.0

robot_state_publisher:
  ros__parameters:
    use_sim_time: false
    publish_frequency: 200.0
    


